### PR TITLE
EJDOTNETCORE-4309 - Update PDF OCR UG documentation - Hotfix

### PR DESCRIPTION
**Pull request by SowmiyaLoganathan**
Hi All, 

I have added the below pages in PDF OCR UG documentation. Kindly review this and merge.
- Windows Forms
- WPF
- AWS Textract
- Azure Vision
- Working with OCR
- Troubleshooting
- Features

Regards,
Sowmiya L

### CODE REVIEW

**Review by praveenHari24 — APPROVED** [review]

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Review by praveenHari24 — APPROVED** [review]

**Pull request merged**
