### PR TITLE
WF-62634 Add UG documentation to convert the PDFA document to a PDF document

### PR DESCRIPTION
**Pull request by Moorthy-K**
Hi @chinnumuniyappan 

Please review the UG documentation changes

Task ID: https://syncfusion.atlassian.net/browse/WF-62634?oldIssueView=true
Content Reviewed Task is linked in the above UG task for your reference

Regards,
Moorthy K

### CODE REVIEW

**Comment by Moorthy-K** [comment]
Hi @DeepakRajSundar 

Still, the same error exists. Can you please guide me through the steps to resolve this error? 

Previous PR:https://github.com/syncfusion-content/fileformat-docs/pull/37 

Regards,
Moorthy K

**Review by chinnumuniyappan — APPROVED** [review]
Fine

**Comment by Moorthy-K** [comment]
Hi @DeepakRajSundar 

Any Updates?

**Comment by Moorthy-K** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Pull request merged**
