### PR TITLE
WF-62494-Removed .NET MAUI limitation in UG documentation

### PR DESCRIPTION
**Pull request by Suriya-Balamurugan**
<h4 id="feature-description">Kindly review the below merge request and let me know if you have any concerns,</h4>
<table style="width: 155px;">
<tbody>
<tr style="height: 86px;">
<td style="width: 37.7396px; height: 86px;">
<h4 id="feature-description">Task link</h4>
</td>
<td style="width: 121.26px; height: 86px;">
<p><a href="https://syncfusion.atlassian.net/browse/WF-62494" rel="nofollow">https://syncfusion.atlassian.net/browse/WF-62494</a></p>
</td>
</tr>
<tr style="height: 56.7917px;">
<td style="width: 37.7396px; height: 56.7917px;">
<h4 id="feature-description">Description</h4>
</td>
<td style="width: 121.26px; height: 56.7917px;">Removed .NET MAUI limitation in UG documentation</td>
</tr>
<tr style="height: 88px;">
<td style="width: 37.7396px; height: 88px;">
<h4 id="solution-description">Changes done</h4>
</td>
<td style="width: 121.26px; height: 88px;">

Removed .NET MAUI limitation in UG documentation for DocIO and Presentation.

</td>
</tr>
</tbody>
</table>

### CODE REVIEW

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Review by MohanaselvamJothi — APPROVED** [review]

**Comment by MohanaselvamJothi** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Pull request merged**
