### PR TITLE
EJDOTNETCORE-4161 Add UG documentation for AWS Textract OCR and github sample

### PR DESCRIPTION
**Pull request by karmegams02**
Hi team,

I have added the UG documentation for performing OCR with AWS Textract.

Regards,
Karmegam

### CODE REVIEW

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Comment by karmegams02** [comment]
rebuild

**Review by PrakashViswanath — APPROVED** [review]
The code changes are fine.

**Pull request merged**
