### PR TITLE
WF-65311 - Update HTML to PDF in document conversion topic - Hotfix

### PR DESCRIPTION
**Pull request by SowmiyaLoganathan**
Hi All, 

I have updated the below in document conversion topic. Kindly review and merge this. 
- FT link 
- code example 
- UG documentation link 

Regards,
Sowmiya L

### CODE REVIEW

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Comment by SowmiyaLoganathan** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by praveen-hari — APPROVED** [review]

**Review by praveenHari24 — APPROVED** [review]

**Pull request merged**
